# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reformers_model_repo_client.models.container_config_config import ContainerConfigConfig

class TestContainerConfigConfig(unittest.TestCase):
    """ContainerConfigConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContainerConfigConfig:
        """Test ContainerConfigConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContainerConfigConfig`
        """
        model = ContainerConfigConfig()
        if include_optional:
            return ContainerConfigConfig(
                env = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],
                cmd = ["/hello"],
                labels = {"generator2.baz2":"qux2","generator2.opt.o-baz2":"o-qux2"}
            )
        else:
            return ContainerConfigConfig(
        )
        """

    def testContainerConfigConfig(self):
        """Test ContainerConfigConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
