# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reformers_model_repo_client.api.retrieve_manifests_api import RetrieveManifestsApi


class TestRetrieveManifestsApi(unittest.TestCase):
    """RetrieveManifestsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RetrieveManifestsApi()

    def tearDown(self) -> None:
        pass

    def test_get_manifest_generator(self) -> None:
        """Test case for get_manifest_generator

        Retrieve manifest of model generator image from the repository.
        """
        pass

    def test_get_manifest_model(self) -> None:
        """Test case for get_manifest_model

        Retrieve manifest of model image from the repository.
        """
        pass


if __name__ == '__main__':
    unittest.main()
