# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reformers_model_repo_client.models.manifest import Manifest

class TestManifest(unittest.TestCase):
    """Manifest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Manifest:
        """Test Manifest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Manifest`
        """
        model = Manifest()
        if include_optional:
            return Manifest(
                schema_version = 2,
                media_type = 'application/vnd.docker.distribution.manifest.v2+json',
                config = {"mediaType":"application/vnd.docker.container.image.v1+json","size":"653","digest":"sha256:d04f4d9ca0a2cf74c4975c36fff511df7e7a74acd73fd390d21ab64b6d00376f"},
                layers = [{"mediaType":"application/vnd.docker.image.rootfs.diff.tar.gzip","size":"2457","digest":"sha256:719385e32844401d57ecfd3eacab360bf551a1491c05b85806ed8f1b08d792f6"}]
            )
        else:
            return Manifest(
        )
        """

    def testManifest(self):
        """Test Manifest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
