# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reformers_model_repo_client.api.handle_artifacts_api import HandleArtifactsApi


class TestHandleArtifactsApi(unittest.TestCase):
    """HandleArtifactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HandleArtifactsApi()

    def tearDown(self) -> None:
        pass

    def test_add_artifact(self) -> None:
        """Test case for add_artifact

        Add artifact (to Maven repository).
        """
        pass

    def test_get_artifact(self) -> None:
        """Test case for get_artifact

        Download model artifact (from Maven repository).
        """
        pass


if __name__ == '__main__':
    unittest.main()
