# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reformers_model_repo_client.models.container_config import ContainerConfig

class TestContainerConfig(unittest.TestCase):
    """ContainerConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContainerConfig:
        """Test ContainerConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContainerConfig`
        """
        model = ContainerConfig()
        if include_optional:
            return ContainerConfig(
                architecture = 'amd64',
                created = '2023-05-04T17:37:03.872958712Z',
                os = 'linux',
                config = reformers_model_repo_client.models.container_config_config.container_config_config(
                    env = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"], 
                    cmd = ["/hello"], 
                    labels = {"generator2.baz2":"qux2","generator2.opt.o-baz2":"o-qux2"}, ),
                history = [{"created":"2023-05-04T17:37:03.801840823Z","created_by":"/bin/sh -c #(nop) COPY file:201f8f1849e89d53be9f6aa76937f5e209d745abfd15a8552fcf2ba45ab267f9 in / "},{"created":"2023-05-04T17:37:03.872958712Z","created_by":"/bin/sh -c #(nop)  CMD [\"/hello\"]","empty_layer":true}]
            )
        else:
            return ContainerConfig(
        )
        """

    def testContainerConfig(self):
        """Test ContainerConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
