# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reformers_model_repo_client.models.manifest_not_found import ManifestNotFound

class TestManifestNotFound(unittest.TestCase):
    """ManifestNotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManifestNotFound:
        """Test ManifestNotFound
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManifestNotFound`
        """
        model = ManifestNotFound()
        if include_optional:
            return ManifestNotFound(
                errors = [
                    reformers_model_repo_client.models.manifest_not_found_errors_inner.manifest_not_found_errors_inner(
                        code = 'MANIFEST_UNKNOWN', 
                        message = 'manifest unknown', 
                        detail = [{"Name":"generator1"},{"Tag":"v234"}], )
                    ]
            )
        else:
            return ManifestNotFound(
        )
        """

    def testManifestNotFound(self):
        """Test ManifestNotFound"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
