# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from reformers_model_repo_client.models.blob_not_found import BlobNotFound

class TestBlobNotFound(unittest.TestCase):
    """BlobNotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlobNotFound:
        """Test BlobNotFound
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlobNotFound`
        """
        model = BlobNotFound()
        if include_optional:
            return BlobNotFound(
                errors = [
                    reformers_model_repo_client.models.blob_not_found_errors_inner.blob_not_found_errors_inner(
                        code = 'BLOB_UNKNOWN', 
                        message = 'blob unknown to registry', 
                        detail = 'sha256:d04f4d9ca0a2cf74c4975c36fff511df7e7a74acd73fd390d21ab64b6d00376c', )
                    ]
            )
        else:
            return BlobNotFound(
        )
        """

    def testBlobNotFound(self):
        """Test BlobNotFound"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
