# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictBool, StrictBytes, StrictStr
from typing import Optional, Tuple, Union

from reformers_model_repo_client.api_client import ApiClient, RequestSerialized
from reformers_model_repo_client.api_response import ApiResponse
from reformers_model_repo_client.rest import RESTResponseType


class AddArtifactsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def add_component(
        self,
        repository: StrictStr,
        version: StrictStr,
        maven2_generate_pom: Optional[StrictBool] = None,
        maven2_group_id: Optional[StrictStr] = None,
        maven2_artifact_id: Optional[StrictStr] = None,
        maven2_asset1: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = None,
        maven2_asset1_extension: Optional[StrictStr] = None,
        maven2_asset2: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = None,
        maven2_asset2_extension: Optional[StrictStr] = None,
        maven2_asset3: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = None,
        maven2_asset3_extension: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Add component (to Maven repository).


        :param repository: (required)
        :type repository: str
        :param version: (required)
        :type version: str
        :param maven2_generate_pom:
        :type maven2_generate_pom: bool
        :param maven2_group_id:
        :type maven2_group_id: str
        :param maven2_artifact_id:
        :type maven2_artifact_id: str
        :param maven2_asset1:
        :type maven2_asset1: bytearray
        :param maven2_asset1_extension:
        :type maven2_asset1_extension: str
        :param maven2_asset2:
        :type maven2_asset2: bytearray
        :param maven2_asset2_extension:
        :type maven2_asset2_extension: str
        :param maven2_asset3:
        :type maven2_asset3: bytearray
        :param maven2_asset3_extension:
        :type maven2_asset3_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._add_component_serialize(
            repository=repository,
            version=version,
            maven2_generate_pom=maven2_generate_pom,
            maven2_group_id=maven2_group_id,
            maven2_artifact_id=maven2_artifact_id,
            maven2_asset1=maven2_asset1,
            maven2_asset1_extension=maven2_asset1_extension,
            maven2_asset2=maven2_asset2,
            maven2_asset2_extension=maven2_asset2_extension,
            maven2_asset3=maven2_asset3,
            maven2_asset3_extension=maven2_asset3_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '401': None,
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def add_component_with_http_info(
        self,
        repository: StrictStr,
        version: StrictStr,
        maven2_generate_pom: Optional[StrictBool] = None,
        maven2_group_id: Optional[StrictStr] = None,
        maven2_artifact_id: Optional[StrictStr] = None,
        maven2_asset1: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = None,
        maven2_asset1_extension: Optional[StrictStr] = None,
        maven2_asset2: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = None,
        maven2_asset2_extension: Optional[StrictStr] = None,
        maven2_asset3: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = None,
        maven2_asset3_extension: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Add component (to Maven repository).


        :param repository: (required)
        :type repository: str
        :param version: (required)
        :type version: str
        :param maven2_generate_pom:
        :type maven2_generate_pom: bool
        :param maven2_group_id:
        :type maven2_group_id: str
        :param maven2_artifact_id:
        :type maven2_artifact_id: str
        :param maven2_asset1:
        :type maven2_asset1: bytearray
        :param maven2_asset1_extension:
        :type maven2_asset1_extension: str
        :param maven2_asset2:
        :type maven2_asset2: bytearray
        :param maven2_asset2_extension:
        :type maven2_asset2_extension: str
        :param maven2_asset3:
        :type maven2_asset3: bytearray
        :param maven2_asset3_extension:
        :type maven2_asset3_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._add_component_serialize(
            repository=repository,
            version=version,
            maven2_generate_pom=maven2_generate_pom,
            maven2_group_id=maven2_group_id,
            maven2_artifact_id=maven2_artifact_id,
            maven2_asset1=maven2_asset1,
            maven2_asset1_extension=maven2_asset1_extension,
            maven2_asset2=maven2_asset2,
            maven2_asset2_extension=maven2_asset2_extension,
            maven2_asset3=maven2_asset3,
            maven2_asset3_extension=maven2_asset3_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '401': None,
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def add_component_without_preload_content(
        self,
        repository: StrictStr,
        version: StrictStr,
        maven2_generate_pom: Optional[StrictBool] = None,
        maven2_group_id: Optional[StrictStr] = None,
        maven2_artifact_id: Optional[StrictStr] = None,
        maven2_asset1: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = None,
        maven2_asset1_extension: Optional[StrictStr] = None,
        maven2_asset2: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = None,
        maven2_asset2_extension: Optional[StrictStr] = None,
        maven2_asset3: Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]] = None,
        maven2_asset3_extension: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Add component (to Maven repository).


        :param repository: (required)
        :type repository: str
        :param version: (required)
        :type version: str
        :param maven2_generate_pom:
        :type maven2_generate_pom: bool
        :param maven2_group_id:
        :type maven2_group_id: str
        :param maven2_artifact_id:
        :type maven2_artifact_id: str
        :param maven2_asset1:
        :type maven2_asset1: bytearray
        :param maven2_asset1_extension:
        :type maven2_asset1_extension: str
        :param maven2_asset2:
        :type maven2_asset2: bytearray
        :param maven2_asset2_extension:
        :type maven2_asset2_extension: str
        :param maven2_asset3:
        :type maven2_asset3: bytearray
        :param maven2_asset3_extension:
        :type maven2_asset3_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._add_component_serialize(
            repository=repository,
            version=version,
            maven2_generate_pom=maven2_generate_pom,
            maven2_group_id=maven2_group_id,
            maven2_artifact_id=maven2_artifact_id,
            maven2_asset1=maven2_asset1,
            maven2_asset1_extension=maven2_asset1_extension,
            maven2_asset2=maven2_asset2,
            maven2_asset2_extension=maven2_asset2_extension,
            maven2_asset3=maven2_asset3,
            maven2_asset3_extension=maven2_asset3_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '401': None,
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _add_component_serialize(
        self,
        repository,
        version,
        maven2_generate_pom,
        maven2_group_id,
        maven2_artifact_id,
        maven2_asset1,
        maven2_asset1_extension,
        maven2_asset2,
        maven2_asset2_extension,
        maven2_asset3,
        maven2_asset3_extension,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if repository is not None:
            
            _query_params.append(('repository', repository))
            
        # process the header parameters
        # process the form parameters
        if version is not None:
            _form_params.append(('version', version))
        if maven2_generate_pom is not None:
            _form_params.append(('maven2.generate-pom', maven2_generate_pom))
        if maven2_group_id is not None:
            _form_params.append(('maven2.groupId', maven2_group_id))
        if maven2_artifact_id is not None:
            _form_params.append(('maven2.artifactId', maven2_artifact_id))
        if maven2_asset1 is not None:
            _files['maven2.asset1'] = maven2_asset1
        if maven2_asset1_extension is not None:
            _form_params.append(('maven2.asset1.extension', maven2_asset1_extension))
        if maven2_asset2 is not None:
            _files['maven2.asset2'] = maven2_asset2
        if maven2_asset2_extension is not None:
            _form_params.append(('maven2.asset2.extension', maven2_asset2_extension))
        if maven2_asset3 is not None:
            _files['maven2.asset3'] = maven2_asset3
        if maven2_asset3_extension is not None:
            _form_params.append(('maven2.asset3.extension', maven2_asset3_extension))
        # process the body parameter



        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'multipart/form-data'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BasicHttpAuthentication'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/service/rest/v1/components',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


