# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictBytes, StrictStr, field_validator
from typing import Optional, Tuple, Union
from typing_extensions import Annotated

from reformers_model_repo_client.api_client import ApiClient, RequestSerialized
from reformers_model_repo_client.api_response import ApiResponse
from reformers_model_repo_client.rest import RESTResponseType


class HandleArtifactsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def add_artifact(
        self,
        repository: Annotated[str, Field(strict=True)],
        version: Annotated[str, Field(strict=True, description="model artifact version")],
        maven2_generate_pom: Annotated[Optional[StrictBool], Field(description="generate a [POM](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) file for artifact")] = None,
        maven2_group_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="group ID")] = None,
        maven2_artifact_id: Annotated[Optional[StrictStr], Field(description="artifact ID")] = None,
        maven2_asset1: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="artifact \\\\#1 file content")] = None,
        maven2_asset1_extension: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#1 file extension")] = None,
        maven2_asset1_classifier: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#1 classifier")] = None,
        maven2_asset2: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="artifact \\\\#2 file content")] = None,
        maven2_asset2_extension: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#2 file extension")] = None,
        maven2_asset2_classifier: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#2 classifier")] = None,
        maven2_asset3: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="artifact \\\\#3 file content")] = None,
        maven2_asset3_extension: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#3 file extension")] = None,
        maven2_asset3_classifier: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#3 classifier")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Add artifact (to Maven repository).


        :param repository: (required)
        :type repository: str
        :param version: model artifact version (required)
        :type version: str
        :param maven2_generate_pom: generate a [POM](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) file for artifact
        :type maven2_generate_pom: bool
        :param maven2_group_id: group ID
        :type maven2_group_id: str
        :param maven2_artifact_id: artifact ID
        :type maven2_artifact_id: str
        :param maven2_asset1: artifact \\\\#1 file content
        :type maven2_asset1: bytearray
        :param maven2_asset1_extension: artifact \\\\#1 file extension
        :type maven2_asset1_extension: str
        :param maven2_asset1_classifier: artifact \\\\#1 classifier
        :type maven2_asset1_classifier: str
        :param maven2_asset2: artifact \\\\#2 file content
        :type maven2_asset2: bytearray
        :param maven2_asset2_extension: artifact \\\\#2 file extension
        :type maven2_asset2_extension: str
        :param maven2_asset2_classifier: artifact \\\\#2 classifier
        :type maven2_asset2_classifier: str
        :param maven2_asset3: artifact \\\\#3 file content
        :type maven2_asset3: bytearray
        :param maven2_asset3_extension: artifact \\\\#3 file extension
        :type maven2_asset3_extension: str
        :param maven2_asset3_classifier: artifact \\\\#3 classifier
        :type maven2_asset3_classifier: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._add_artifact_serialize(
            repository=repository,
            version=version,
            maven2_generate_pom=maven2_generate_pom,
            maven2_group_id=maven2_group_id,
            maven2_artifact_id=maven2_artifact_id,
            maven2_asset1=maven2_asset1,
            maven2_asset1_extension=maven2_asset1_extension,
            maven2_asset1_classifier=maven2_asset1_classifier,
            maven2_asset2=maven2_asset2,
            maven2_asset2_extension=maven2_asset2_extension,
            maven2_asset2_classifier=maven2_asset2_classifier,
            maven2_asset3=maven2_asset3,
            maven2_asset3_extension=maven2_asset3_extension,
            maven2_asset3_classifier=maven2_asset3_classifier,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '401': None,
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def add_artifact_with_http_info(
        self,
        repository: Annotated[str, Field(strict=True)],
        version: Annotated[str, Field(strict=True, description="model artifact version")],
        maven2_generate_pom: Annotated[Optional[StrictBool], Field(description="generate a [POM](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) file for artifact")] = None,
        maven2_group_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="group ID")] = None,
        maven2_artifact_id: Annotated[Optional[StrictStr], Field(description="artifact ID")] = None,
        maven2_asset1: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="artifact \\\\#1 file content")] = None,
        maven2_asset1_extension: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#1 file extension")] = None,
        maven2_asset1_classifier: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#1 classifier")] = None,
        maven2_asset2: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="artifact \\\\#2 file content")] = None,
        maven2_asset2_extension: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#2 file extension")] = None,
        maven2_asset2_classifier: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#2 classifier")] = None,
        maven2_asset3: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="artifact \\\\#3 file content")] = None,
        maven2_asset3_extension: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#3 file extension")] = None,
        maven2_asset3_classifier: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#3 classifier")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Add artifact (to Maven repository).


        :param repository: (required)
        :type repository: str
        :param version: model artifact version (required)
        :type version: str
        :param maven2_generate_pom: generate a [POM](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) file for artifact
        :type maven2_generate_pom: bool
        :param maven2_group_id: group ID
        :type maven2_group_id: str
        :param maven2_artifact_id: artifact ID
        :type maven2_artifact_id: str
        :param maven2_asset1: artifact \\\\#1 file content
        :type maven2_asset1: bytearray
        :param maven2_asset1_extension: artifact \\\\#1 file extension
        :type maven2_asset1_extension: str
        :param maven2_asset1_classifier: artifact \\\\#1 classifier
        :type maven2_asset1_classifier: str
        :param maven2_asset2: artifact \\\\#2 file content
        :type maven2_asset2: bytearray
        :param maven2_asset2_extension: artifact \\\\#2 file extension
        :type maven2_asset2_extension: str
        :param maven2_asset2_classifier: artifact \\\\#2 classifier
        :type maven2_asset2_classifier: str
        :param maven2_asset3: artifact \\\\#3 file content
        :type maven2_asset3: bytearray
        :param maven2_asset3_extension: artifact \\\\#3 file extension
        :type maven2_asset3_extension: str
        :param maven2_asset3_classifier: artifact \\\\#3 classifier
        :type maven2_asset3_classifier: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._add_artifact_serialize(
            repository=repository,
            version=version,
            maven2_generate_pom=maven2_generate_pom,
            maven2_group_id=maven2_group_id,
            maven2_artifact_id=maven2_artifact_id,
            maven2_asset1=maven2_asset1,
            maven2_asset1_extension=maven2_asset1_extension,
            maven2_asset1_classifier=maven2_asset1_classifier,
            maven2_asset2=maven2_asset2,
            maven2_asset2_extension=maven2_asset2_extension,
            maven2_asset2_classifier=maven2_asset2_classifier,
            maven2_asset3=maven2_asset3,
            maven2_asset3_extension=maven2_asset3_extension,
            maven2_asset3_classifier=maven2_asset3_classifier,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '401': None,
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def add_artifact_without_preload_content(
        self,
        repository: Annotated[str, Field(strict=True)],
        version: Annotated[str, Field(strict=True, description="model artifact version")],
        maven2_generate_pom: Annotated[Optional[StrictBool], Field(description="generate a [POM](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) file for artifact")] = None,
        maven2_group_id: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="group ID")] = None,
        maven2_artifact_id: Annotated[Optional[StrictStr], Field(description="artifact ID")] = None,
        maven2_asset1: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="artifact \\\\#1 file content")] = None,
        maven2_asset1_extension: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#1 file extension")] = None,
        maven2_asset1_classifier: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#1 classifier")] = None,
        maven2_asset2: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="artifact \\\\#2 file content")] = None,
        maven2_asset2_extension: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#2 file extension")] = None,
        maven2_asset2_classifier: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#2 classifier")] = None,
        maven2_asset3: Annotated[Optional[Union[StrictBytes, StrictStr, Tuple[StrictStr, StrictBytes]]], Field(description="artifact \\\\#3 file content")] = None,
        maven2_asset3_extension: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#3 file extension")] = None,
        maven2_asset3_classifier: Annotated[Optional[Annotated[str, Field(strict=True)]], Field(description="artifact \\\\#3 classifier")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Add artifact (to Maven repository).


        :param repository: (required)
        :type repository: str
        :param version: model artifact version (required)
        :type version: str
        :param maven2_generate_pom: generate a [POM](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) file for artifact
        :type maven2_generate_pom: bool
        :param maven2_group_id: group ID
        :type maven2_group_id: str
        :param maven2_artifact_id: artifact ID
        :type maven2_artifact_id: str
        :param maven2_asset1: artifact \\\\#1 file content
        :type maven2_asset1: bytearray
        :param maven2_asset1_extension: artifact \\\\#1 file extension
        :type maven2_asset1_extension: str
        :param maven2_asset1_classifier: artifact \\\\#1 classifier
        :type maven2_asset1_classifier: str
        :param maven2_asset2: artifact \\\\#2 file content
        :type maven2_asset2: bytearray
        :param maven2_asset2_extension: artifact \\\\#2 file extension
        :type maven2_asset2_extension: str
        :param maven2_asset2_classifier: artifact \\\\#2 classifier
        :type maven2_asset2_classifier: str
        :param maven2_asset3: artifact \\\\#3 file content
        :type maven2_asset3: bytearray
        :param maven2_asset3_extension: artifact \\\\#3 file extension
        :type maven2_asset3_extension: str
        :param maven2_asset3_classifier: artifact \\\\#3 classifier
        :type maven2_asset3_classifier: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._add_artifact_serialize(
            repository=repository,
            version=version,
            maven2_generate_pom=maven2_generate_pom,
            maven2_group_id=maven2_group_id,
            maven2_artifact_id=maven2_artifact_id,
            maven2_asset1=maven2_asset1,
            maven2_asset1_extension=maven2_asset1_extension,
            maven2_asset1_classifier=maven2_asset1_classifier,
            maven2_asset2=maven2_asset2,
            maven2_asset2_extension=maven2_asset2_extension,
            maven2_asset2_classifier=maven2_asset2_classifier,
            maven2_asset3=maven2_asset3,
            maven2_asset3_extension=maven2_asset3_extension,
            maven2_asset3_classifier=maven2_asset3_classifier,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '401': None,
            '404': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _add_artifact_serialize(
        self,
        repository,
        version,
        maven2_generate_pom,
        maven2_group_id,
        maven2_artifact_id,
        maven2_asset1,
        maven2_asset1_extension,
        maven2_asset1_classifier,
        maven2_asset2,
        maven2_asset2_extension,
        maven2_asset2_classifier,
        maven2_asset3,
        maven2_asset3_extension,
        maven2_asset3_classifier,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if repository is not None:
            
            _query_params.append(('repository', repository))
            
        # process the header parameters
        # process the form parameters
        if version is not None:
            _form_params.append(('version', version))
        if maven2_generate_pom is not None:
            _form_params.append(('maven2.generate-pom', maven2_generate_pom))
        if maven2_group_id is not None:
            _form_params.append(('maven2.groupId', maven2_group_id))
        if maven2_artifact_id is not None:
            _form_params.append(('maven2.artifactId', maven2_artifact_id))
        if maven2_asset1 is not None:
            _files['maven2.asset1'] = maven2_asset1
        if maven2_asset1_extension is not None:
            _form_params.append(('maven2.asset1.extension', maven2_asset1_extension))
        if maven2_asset1_classifier is not None:
            _form_params.append(('maven2.asset1.classifier', maven2_asset1_classifier))
        if maven2_asset2 is not None:
            _files['maven2.asset2'] = maven2_asset2
        if maven2_asset2_extension is not None:
            _form_params.append(('maven2.asset2.extension', maven2_asset2_extension))
        if maven2_asset2_classifier is not None:
            _form_params.append(('maven2.asset2.classifier', maven2_asset2_classifier))
        if maven2_asset3 is not None:
            _files['maven2.asset3'] = maven2_asset3
        if maven2_asset3_extension is not None:
            _form_params.append(('maven2.asset3.extension', maven2_asset3_extension))
        if maven2_asset3_classifier is not None:
            _form_params.append(('maven2.asset3.classifier', maven2_asset3_classifier))
        # process the body parameter



        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'multipart/form-data'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BasicHttpAuthentication'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/service/rest/v1/components',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_artifact(
        self,
        generator_name: Annotated[str, Field(strict=True)],
        generator_tag: Annotated[str, Field(strict=True)],
        model_name: Annotated[str, Field(strict=True)],
        model_tag: Annotated[str, Field(strict=True)],
        file_name: Annotated[str, Field(strict=True)],
        file_extension: Annotated[str, Field(strict=True)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> bytearray:
        """Download model artifact (from Maven repository).


        :param generator_name: (required)
        :type generator_name: str
        :param generator_tag: (required)
        :type generator_tag: str
        :param model_name: (required)
        :type model_name: str
        :param model_tag: (required)
        :type model_tag: str
        :param file_name: (required)
        :type file_name: str
        :param file_extension: (required)
        :type file_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_artifact_serialize(
            generator_name=generator_name,
            generator_tag=generator_tag,
            model_name=model_name,
            model_tag=model_tag,
            file_name=file_name,
            file_extension=file_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytearray",
            '404': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_artifact_with_http_info(
        self,
        generator_name: Annotated[str, Field(strict=True)],
        generator_tag: Annotated[str, Field(strict=True)],
        model_name: Annotated[str, Field(strict=True)],
        model_tag: Annotated[str, Field(strict=True)],
        file_name: Annotated[str, Field(strict=True)],
        file_extension: Annotated[str, Field(strict=True)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[bytearray]:
        """Download model artifact (from Maven repository).


        :param generator_name: (required)
        :type generator_name: str
        :param generator_tag: (required)
        :type generator_tag: str
        :param model_name: (required)
        :type model_name: str
        :param model_tag: (required)
        :type model_tag: str
        :param file_name: (required)
        :type file_name: str
        :param file_extension: (required)
        :type file_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_artifact_serialize(
            generator_name=generator_name,
            generator_tag=generator_tag,
            model_name=model_name,
            model_tag=model_tag,
            file_name=file_name,
            file_extension=file_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytearray",
            '404': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_artifact_without_preload_content(
        self,
        generator_name: Annotated[str, Field(strict=True)],
        generator_tag: Annotated[str, Field(strict=True)],
        model_name: Annotated[str, Field(strict=True)],
        model_tag: Annotated[str, Field(strict=True)],
        file_name: Annotated[str, Field(strict=True)],
        file_extension: Annotated[str, Field(strict=True)],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Download model artifact (from Maven repository).


        :param generator_name: (required)
        :type generator_name: str
        :param generator_tag: (required)
        :type generator_tag: str
        :param model_name: (required)
        :type model_name: str
        :param model_tag: (required)
        :type model_tag: str
        :param file_name: (required)
        :type file_name: str
        :param file_extension: (required)
        :type file_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_artifact_serialize(
            generator_name=generator_name,
            generator_tag=generator_tag,
            model_name=model_name,
            model_tag=model_tag,
            file_name=file_name,
            file_extension=file_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytearray",
            '404': "str",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_artifact_serialize(
        self,
        generator_name,
        generator_tag,
        model_name,
        model_tag,
        file_name,
        file_extension,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if generator_name is not None:
            _path_params['generator-name'] = generator_name
        if generator_tag is not None:
            _path_params['generator-tag'] = generator_tag
        if model_name is not None:
            _path_params['model-name'] = model_name
        if model_tag is not None:
            _path_params['model-tag'] = model_tag
        if file_name is not None:
            _path_params['file-name'] = file_name
        if file_extension is not None:
            _path_params['file-extension'] = file_extension
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    '*', 
                    'text/html'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'NoAuthentication'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/repository/model-artifacts/{generator-name}/{generator-tag}/{model-name}/{model-tag}/{file-name}.{file-extension}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


