# coding: utf-8

"""
    REFORMERS Digital Twin: Model Repository API

    This API provides access to the REFORMERS Digital Twin Model Repository.  _Funding acknowledgement_: The [REFORMERS project](https://reformers-energyvalleys.eu) has received funding from the European Union’s research and innovation programme Horizon Europe under the [Grant Agreement No.101136211](https://cordis.europa.eu/project/id/101136211) 

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictStr, field_validator
from typing import Optional
from reformers_model_repo_client.models.repository_search_result import RepositorySearchResult

from reformers_model_repo_client.api_client import ApiClient, RequestSerialized
from reformers_model_repo_client.api_response import ApiResponse
from reformers_model_repo_client.rest import RESTResponseType


class SearchRepositoryApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def search_assets(
        self,
        continuation_token: Optional[StrictStr] = None,
        repository: Optional[StrictStr] = None,
        format: Optional[StrictStr] = None,
        group: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        version: Optional[StrictStr] = None,
        docker_image_tag: Optional[StrictStr] = None,
        maven_extension: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RepositorySearchResult:
        """Retrieve information about available assets in the repository.


        :param continuation_token:
        :type continuation_token: str
        :param repository:
        :type repository: str
        :param format:
        :type format: str
        :param group:
        :type group: str
        :param name:
        :type name: str
        :param version:
        :type version: str
        :param docker_image_tag:
        :type docker_image_tag: str
        :param maven_extension:
        :type maven_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_assets_serialize(
            continuation_token=continuation_token,
            repository=repository,
            format=format,
            group=group,
            name=name,
            version=version,
            docker_image_tag=docker_image_tag,
            maven_extension=maven_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RepositorySearchResult",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_assets_with_http_info(
        self,
        continuation_token: Optional[StrictStr] = None,
        repository: Optional[StrictStr] = None,
        format: Optional[StrictStr] = None,
        group: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        version: Optional[StrictStr] = None,
        docker_image_tag: Optional[StrictStr] = None,
        maven_extension: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[RepositorySearchResult]:
        """Retrieve information about available assets in the repository.


        :param continuation_token:
        :type continuation_token: str
        :param repository:
        :type repository: str
        :param format:
        :type format: str
        :param group:
        :type group: str
        :param name:
        :type name: str
        :param version:
        :type version: str
        :param docker_image_tag:
        :type docker_image_tag: str
        :param maven_extension:
        :type maven_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_assets_serialize(
            continuation_token=continuation_token,
            repository=repository,
            format=format,
            group=group,
            name=name,
            version=version,
            docker_image_tag=docker_image_tag,
            maven_extension=maven_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RepositorySearchResult",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_assets_without_preload_content(
        self,
        continuation_token: Optional[StrictStr] = None,
        repository: Optional[StrictStr] = None,
        format: Optional[StrictStr] = None,
        group: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        version: Optional[StrictStr] = None,
        docker_image_tag: Optional[StrictStr] = None,
        maven_extension: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieve information about available assets in the repository.


        :param continuation_token:
        :type continuation_token: str
        :param repository:
        :type repository: str
        :param format:
        :type format: str
        :param group:
        :type group: str
        :param name:
        :type name: str
        :param version:
        :type version: str
        :param docker_image_tag:
        :type docker_image_tag: str
        :param maven_extension:
        :type maven_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_assets_serialize(
            continuation_token=continuation_token,
            repository=repository,
            format=format,
            group=group,
            name=name,
            version=version,
            docker_image_tag=docker_image_tag,
            maven_extension=maven_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RepositorySearchResult",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_assets_serialize(
        self,
        continuation_token,
        repository,
        format,
        group,
        name,
        version,
        docker_image_tag,
        maven_extension,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if continuation_token is not None:
            
            _query_params.append(('continuationToken', continuation_token))
            
        if repository is not None:
            
            _query_params.append(('repository', repository))
            
        if format is not None:
            
            _query_params.append(('format', format))
            
        if group is not None:
            
            _query_params.append(('group', group))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if version is not None:
            
            _query_params.append(('version', version))
            
        if docker_image_tag is not None:
            
            _query_params.append(('docker.imageTag', docker_image_tag))
            
        if maven_extension is not None:
            
            _query_params.append(('maven.extension', maven_extension))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'NoAuthentication'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/service/rest/v1/search/assets',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def search_components(
        self,
        continuation_token: Optional[StrictStr] = None,
        repository: Optional[StrictStr] = None,
        format: Optional[StrictStr] = None,
        group: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        version: Optional[StrictStr] = None,
        docker_image_tag: Optional[StrictStr] = None,
        maven_extension: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RepositorySearchResult:
        """Retrieve information about available components in the repository.


        :param continuation_token:
        :type continuation_token: str
        :param repository:
        :type repository: str
        :param format:
        :type format: str
        :param group:
        :type group: str
        :param name:
        :type name: str
        :param version:
        :type version: str
        :param docker_image_tag:
        :type docker_image_tag: str
        :param maven_extension:
        :type maven_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_components_serialize(
            continuation_token=continuation_token,
            repository=repository,
            format=format,
            group=group,
            name=name,
            version=version,
            docker_image_tag=docker_image_tag,
            maven_extension=maven_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RepositorySearchResult",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_components_with_http_info(
        self,
        continuation_token: Optional[StrictStr] = None,
        repository: Optional[StrictStr] = None,
        format: Optional[StrictStr] = None,
        group: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        version: Optional[StrictStr] = None,
        docker_image_tag: Optional[StrictStr] = None,
        maven_extension: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[RepositorySearchResult]:
        """Retrieve information about available components in the repository.


        :param continuation_token:
        :type continuation_token: str
        :param repository:
        :type repository: str
        :param format:
        :type format: str
        :param group:
        :type group: str
        :param name:
        :type name: str
        :param version:
        :type version: str
        :param docker_image_tag:
        :type docker_image_tag: str
        :param maven_extension:
        :type maven_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_components_serialize(
            continuation_token=continuation_token,
            repository=repository,
            format=format,
            group=group,
            name=name,
            version=version,
            docker_image_tag=docker_image_tag,
            maven_extension=maven_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RepositorySearchResult",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_components_without_preload_content(
        self,
        continuation_token: Optional[StrictStr] = None,
        repository: Optional[StrictStr] = None,
        format: Optional[StrictStr] = None,
        group: Optional[StrictStr] = None,
        name: Optional[StrictStr] = None,
        version: Optional[StrictStr] = None,
        docker_image_tag: Optional[StrictStr] = None,
        maven_extension: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieve information about available components in the repository.


        :param continuation_token:
        :type continuation_token: str
        :param repository:
        :type repository: str
        :param format:
        :type format: str
        :param group:
        :type group: str
        :param name:
        :type name: str
        :param version:
        :type version: str
        :param docker_image_tag:
        :type docker_image_tag: str
        :param maven_extension:
        :type maven_extension: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_components_serialize(
            continuation_token=continuation_token,
            repository=repository,
            format=format,
            group=group,
            name=name,
            version=version,
            docker_image_tag=docker_image_tag,
            maven_extension=maven_extension,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RepositorySearchResult",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_components_serialize(
        self,
        continuation_token,
        repository,
        format,
        group,
        name,
        version,
        docker_image_tag,
        maven_extension,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if continuation_token is not None:
            
            _query_params.append(('continuationToken', continuation_token))
            
        if repository is not None:
            
            _query_params.append(('repository', repository))
            
        if format is not None:
            
            _query_params.append(('format', format))
            
        if group is not None:
            
            _query_params.append(('group', group))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if version is not None:
            
            _query_params.append(('version', version))
            
        if docker_image_tag is not None:
            
            _query_params.append(('docker.imageTag', docker_image_tag))
            
        if maven_extension is not None:
            
            _query_params.append(('maven.extension', maven_extension))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'NoAuthentication'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/service/rest/v1/search',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


